### ISSUE TITLE
Does this works only with dataset provided?

### ISSUE THREAD

**Issue by spkprav** [scorpionhiccup/StockPricePrediction#1]
Hi, 

I would like to test this with Indian NSE market.
Will this works only with the dataset provided by you?

Do you have any scripts written to get data online and run through this?
If it's already included, please provide the steps to get the data.

Thanks in advance.

**Comment by scorpionhiccup** [comment]
Sure it will work on any dataset. Just add the required fields according to those needed in the [Main file](https://github.com/scorpionhiccup/StockPricePrediction/blob/master/scripts/main.py).

**Comment by scorpionhiccup** [comment]
Also, look into the [file](https://github.com/scorpionhiccup/StockPricePrediction/blob/master/scripts/fetch_stock_data.py) for fetching data. On executing the above file it will fetch the data online. 


The params file is given [here](https://github.com/scorpionhiccup/StockPricePrediction/blob/master/input/params.txt)

You just need to pass as argument both the symbols file with newline seperated symbols (for example, 
BHARTI for Bharti Airtel Limited) and the params(field values) that you need as arguement to this [file](https://github.com/scorpionhiccup/StockPricePrediction/blob/master/scripts/fetch_stock_data.py).

Hope this helps.

**Comment by spkprav** [comment]
@scorpionhiccup Thank you for the response, I will test it out and let you know if I have any issues.

Do you use this script for daily trading?

**Comment by spkprav** [comment]
@scorpionhiccup I tried to fetch Indian scripts, but ychart doesn't provide Indian script data.
please suggest.

**Comment by scorpionhiccup** [comment]
Hi,

You can refer to this [link](https://www.quora.com/Is-there-a-real-time-stock-market-data-feed-API-for-NSE-BSE-Mcx-to-implement-in-our-custom-software) for APIs for fetching stock prices for Indian scripts. 

However, most appear to be paid services.

**Comment by scorpionhiccup** [comment]
But, if you have the entire stock market information in say a CSV file, you can certainly use the other scripts to apply machine learning models on the same.
