### ISSUE TITLE
windows

### ISSUE THREAD

**Issue by vedang107** [scorpionhiccup/StockPricePrediction#2]
Hi, can you tell me how to run this on windows?

**Comment by scorpionhiccup** [comment]
Hi,

You could install pip in windows by following the instructions in this [link](https://github.com/BurntSushi/nfldb/wiki/Python-&-pip-Windows-installation)
 
Rest of the steps should be the same. 

Pls. let me know if you face any issues.

**Comment by scorpionhiccup** [comment]
Another Optional Installation is virtualenv. In order to install it in windows, follow [this link](http://pymote.readthedocs.io/en/latest/install/windows_virtualenv.html)

Hope this helps.
