### ISSUE TITLE
can you provide data FB.csv you used in stock market prediction

### ISSUE THREAD

**Issue by abhilashreddyy** [scorpionhiccup/StockPricePrediction#3]

**Comment by scorpionhiccup** [comment]
You can generate the file FB.csv for all the stock prices from 1990 to present time using the script fetch_stock_data.py. It requires as input 3 things:

1. params file: This file contains the information that you want to fetch via the stock prediction api like ps_ratio, dividend_yield, etc. An example for this file is in the input directory of the project source directory.
2. symbols file: This is a text file with the symbols that you want the output of seperated by newlines.
3. output dir: path to output directory. In this directory the files will be created and saved as symbol_1.csv,  symbol_2.csv, etc.
