### ISSUE TITLE
Where did 50_day_moving_avg column come from ??

### ISSUE THREAD

**Issue by HanyHossny** [scorpionhiccup/StockPricePrediction#5]
How did you calculate the columns (50_day_moving_avg, 10_day_volatility)? Did you extract them from the standard four columns (open, close, high, low) by any means?

**Comment by scorpionhiccup** [comment]
Hi @HanyHossny, we had calculated 50_day_moving_avg by calculating rolling_mean over 50 days using the package pandas. I don't have the script for the same but you can easily write the same. Have a look at this [stackoverflow question](https://stackoverflow.com/questions/43437657/rolling-mean-on-pandas-on-a-specific-column) to get a rough idea.
